steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'Authorization', '--trigger-http', '--runtime', 'nodejs10', '--entry-point', 'Authorization']
  dir: 'functions'
  env:
    - 'client_id=us-east1-b'
    - 'redirect_uri=node-example-cluster'
